### PR TITLE
Test on Node.js v0.12.x, v4.x.x, and v5.x.x

### PR DESCRIPTION
**Pull request by ntwb**

### CODE REVIEW

**Comment by magsout** [comment]
cssnext is deprecated soon, so I don' think it's helpful.

**Comment by MoOx** [comment]
This will become the main repo so this will :)
Will handle that when I will be on my computer.

**Comment by magsout** [comment]
Oh god, I didn't see that this PR #238 is in this repo... :sleeping:

**Comment by MoOx** [comment]
Thanks @ntwb!

**Pull request merged**
